development:
  clients:
    default:
      # MONGODB_URI includes draft_content_store_development or content_store_development
      # depending on whether we're running content store in draft mode or not.
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost/specialist_publisher_development' %>
      options:
        write:
          w: 1

test:
  clients:
    default:
      uri: mongodb://localhost/specialist_publisher_test
      options:
        write:
          w: 1
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
